### ISSUE TITLE
install python bindings independently of the python version

### ISSUE THREAD

**Issue by looooo** [conda-forge/pastix-feedstock#2]
### Comment:

currently pastix installs python bindings to python3.12 (which it somehow finds, it's not added as a dependency). As the python bindings are done via ctypes it should be possible to make the build independent of the python version. So my question is: Is there a way to install the python-files to make the package work for different versions of python?
@conda-forge/core

ideally the additional python files would be a noarch package.

**Comment by hmaarrfk** [comment]
Do you want to rerender and add a test section with the command

echo hi


And we can debug there

**Comment by looooo** [comment]
https://github.com/conda-forge/pastix-feedstock/pull/3

**Comment by looooo** [comment]
hopefully this explains what is the problem here

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by looooo** [comment]
the spm python bindings are not yet build as a noarch package.

**Comment by hmaarrfk** [comment]
But the recipe is likely good enough at this stage right?
